// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwyu-nJJT9vKIte5MkTUGqJzAAskAOaFQ',
    appId: '1:633917802122:web:a0607164e241c9b6860f73',
    messagingSenderId: '633917802122',
    projectId: 'chatboot-d26a2',
    authDomain: 'chatboot-d26a2.firebaseapp.com',
    storageBucket: 'chatboot-d26a2.firebasestorage.app',
    measurementId: 'G-DS30Y0H8MN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWlBO8zujyQa7BtTlPvjatJVZSGIR0KBs',
    appId: '1:633917802122:android:81ccc1d46a30ec52860f73',
    messagingSenderId: '633917802122',
    projectId: 'chatboot-d26a2',
    storageBucket: 'chatboot-d26a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBh-LVH2ceheJv7ihnI8gKwIL3j6ofBV6s',
    appId: '1:633917802122:ios:56ea5b5a22cdf2f5860f73',
    messagingSenderId: '633917802122',
    projectId: 'chatboot-d26a2',
    storageBucket: 'chatboot-d26a2.firebasestorage.app',
    iosBundleId: 'com.example.chatboot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBh-LVH2ceheJv7ihnI8gKwIL3j6ofBV6s',
    appId: '1:633917802122:ios:56ea5b5a22cdf2f5860f73',
    messagingSenderId: '633917802122',
    projectId: 'chatboot-d26a2',
    storageBucket: 'chatboot-d26a2.firebasestorage.app',
    iosBundleId: 'com.example.chatboot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwyu-nJJT9vKIte5MkTUGqJzAAskAOaFQ',
    appId: '1:633917802122:web:fe17abd73777556c860f73',
    messagingSenderId: '633917802122',
    projectId: 'chatboot-d26a2',
    authDomain: 'chatboot-d26a2.firebaseapp.com',
    storageBucket: 'chatboot-d26a2.firebasestorage.app',
    measurementId: 'G-2YG96CJ7YS',
  );
}
